health-monitor:
  # unhealthy_threshold is the number of consecutive health checks that must fail
  # before a backend is considered unhealthy. A typical range is 1-5.
  # Default: 3
  unhealthy_threshold: 3
  # healthy_threshold is the number of consecutive health checks that must pass
  # before a backend is considered healthy. A typical range is 1-5.
  # Default: 2
  healthy_threshold: 2
  # interval is the time between health checks. This defines how frequently
  # the health check runs. The value should be in a duration format (e.g., "10s", "1m").
  # Default: 30s
  interval: 30s
  # timeout is the maximum time to wait for a response from the backend before
  # considering it unhealthy.
  # If the timeout is greater than 2/3 the interval, the timeout is set to 2/3 the interval
  #	to avoid unnecessary waiting & deadlocks.
  # The value should be in a duration format (e.g., "2s", "5s").
  # Default: 5s
  timeout: 5s
  # healthy_initially is a flag that indicates whether the backend should be considered
  # healthy when first added, before any health checks.
  # Default: true
  healthy_initially: true
  # accept_status_codes is a list of HTTP status code REGEX PATTERNS that indicate a healthy response.
  # This field is only relevant for HTTP/HTTPS health checks.
  # Example: [200, 201, 202] means status codes 200, 201, and 202 are considered healthy.
  # Default: [2*+] (any 2xx status code)
  accept_status_codes:
    - 200

  # list of backends that will be registered when health monitor starts
  backends:
      # name is the name of the backend. Must be unique.
    - name: backend1
      # url is the URL of the backend. This is the destination that the health check will hit.
      url: http://localhost:8080/health
      # protocol is the protocol to use for health checks. Possible values are:
      # - http: Use HTTP for health checks.
      # - https: Use HTTPS for health checks.
      # - tcp: Use TCP for health checks.
      # - icmp: Use ICMP for health checks (i.e., ping).
      # Default: "http"
      protocol: http
      # attributes below override the global health-monitor settings for this backend
      timeout: 5s
      accepted_status_codes:
        - 200
      unhealthy_threshold: 3
      healthy_threshold: 2

    - name: backend2
      url: http://localhost:8081/health
      protocol: http
